In [14]:
# NumPy Basics
!pip install numpy
### This notebook covers fundamental NumPy concepts used in Machine Learning, including array creation, indexing, vectorized operations, and basic statistics.


'pip' is not recognized as an internal or external command,
operable program or batch file.


In [1]:
import numpy as np

## Array Creation

NumPy arrays are faster and more memory-efficient than Python lists and are the foundation of numerical computing in machine learning.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros(5)
c = np.ones(5)
d = np.arange(0, 10, 2)

a, b, c, d


(array([1, 2, 3, 4, 5]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([0, 2, 4, 6, 8]))

In [ ]:
## Shape and Data Type

Understanding the shape and data type of arrays is important for building machine learning models.


In [4]:
a.shape, a.dtype


((5,), dtype('int64'))

In [ ]:
## Indexing and Slicing

Indexing allows access to specific elements, while slicing extracts subsets of data.


In [5]:
arr = np.array([10, 20, 30, 40, 50])

arr[0], arr[-1], arr[1:4]


(np.int64(10), np.int64(50), array([20, 30, 40]))

In [ ]:
## Vectorized Operations

NumPy performs operations on entire arrays without explicit loops, which is faster and cleaner.


In [6]:
x = np.array([1, 2, 3, 4])

x + 5, x * 2, x ** 2


(array([6, 7, 8, 9]), array([2, 4, 6, 8]), array([ 1,  4,  9, 16]))

In [ ]:
## Broadcasting

Broadcasting allows NumPy to operate on arrays of different shapes.


In [7]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])

matrix + vector


array([[11, 22],
       [13, 24]])

In [ ]:
## Basic Statistics

Statistical operations are commonly used during data preprocessing and analysis.


In [8]:
data = np.array([5, 10, 15, 20, 25])

data.mean(), data.std(), data.min(), data.max()


(np.float64(15.0), np.float64(7.0710678118654755), np.int64(5), np.int64(25))

In [ ]:
## Reshaping Arrays

Reshaping changes the structure of data without changing its content.


In [9]:
r = np.arange(1, 7)
r.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## Summary

This notebook introduced NumPy arrays, indexing, vectorized operations, broadcasting, and basic statistics, which are essential for machine learning workflows.
